name: Build images

on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out your repository using v4 (if/when available)
      - uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt upgrade -y
          sudo apt install -y parted wget dosfstools zip

      # Build Images
      - name: Build Raspberry Pi 5 AArch64 Image
        run: |
          sudo bash create-image aarch64 8G
          sudo cp rpi-aarch64-archlinux.img rpi-5-aarch64-archlinux.img
          zip -v rpi-5-aarch64-archlinux.img.zip rpi-5-aarch64-archlinux.img

      # (Optional) Upload as workflow artifact using v4 (if/when available)
      - name: Upload Raspberry Pi 5 AArch64 Image artifact
        uses: actions/upload-artifact@v4
        with:
          name: rpi-5-aarch64-archlinux.img.zip
          path: rpi-5-aarch64-archlinux.img.zip

      # Create a GitHub Release (runs on tag push)
      - name: Create GitHub Release
        if: startsWith(github.ref, 'refs/tags/')
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref_name }}
          release_name: "Release ${{ github.ref_name }}"
          body: "Automated release for ${{ github.ref_name }}"
          draft: false
          prerelease: false

      # Upload the .zip file to the GitHub Release
      - name: Upload Release Asset
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: rpi-5-aarch64-archlinux.img.zip
          asset_name: rpi-5-aarch64-archlinux.img.zip
          asset_content_type: application/zip
